user_manual: Modify how to use dfu-util
open-degu/open-degu.github.io pull request #13
Opened 2019-07-23 01:03 UTC by takumiando

2019-07-23 04:31 UTC, ohsawa requested changes

2019-07-23 04:31 UTC, ohsawa commented on user_manual/20_software_update.md
> +    # dfu-util --alt 1 -D degu.bin
プロンプトでroot権限を示すと誤解されそうなので、
$ sudo dfu-util ...
の方が良くないです？

2019-07-23 04:31 UTC, ohsawa commented on user_manual/20_software_update.md
> +# apt-get update
こっちも
$ sudo apt-get ...
で権限明示で。

2019-07-23 04:31 UTC, ohsawa commented on user_manual/20_software_update.md
> +$ sudo dpkg -i dfu-util_[VERSION]_[ARCH].deb
これはOK

2019-07-24 09:40 UTC, takumiando commented
Fixed them.

2019-07-25 04:01 UTC, merged