add for specification v1.0.0
open-degu/open-degu.github.io pull request #22
Opened 2020-01-07 06:30 UTC by yoshidam-at

change certificate settings for Degu Gateway(RSA -> ECC)

2020-01-08 01:11 UTC, atKeitaroTakahashi commented on user_manual/30_setup.md
> +```
Numbered list need indent.

2020-01-08 01:11 UTC, atKeitaroTakahashi commented on user_manual/30_setup.md
> +```
```suggestion
    ```
    openssl ecparam -genkey -name prime256v1 -out ca.pem.key
    ```
```

2020-01-08 01:34 UTC, ohsawa requested changes

2020-01-08 01:34 UTC, ohsawa commented on user_manual/30_setup.md
> +    * gw: preset: device: cert
初出箇所で、全部説明したくなる気持ちは分かるのですが、
ここでユーザーは「必要があれば」をどのように判断すれば
良いのかわからないです。

編集の必要な条件を明示するか、それを明示すると手順が煩雑になるのであれば
「間違いなく動作する理想の手順と例」を示した後に
「オプショナルな設定を要する事例と変更箇所」としたほうが、
理解しやすくや中途半端に変更したことによるスタックを防ぐことが出来ます。

2020-01-08 01:43 UTC, ohsawa commented on user_manual/30_setup.md
> +デバイス証明書を設置しない場合、Deguゲートウェイがデバイス証明書を自動生成しますので、必ず指定してください。
デバイス証明書を設置する場合/しない場合の2パタンしか無いことは
ユーザーにとっては自明ではないと思います。

手順に沿って設定していくとき、自分が何を変更するべきか、
あるいは後で試行錯誤するとき、設定の正しい組み合わせは
何か(同時に変更するパラメタは何か)がわからないと、ストレス
とミスの原因になります。

手順の最初に、「AとB、2つの使い方があります。それぞれ特徴は...」とした上で、
Aの使い方、Bの使い方それぞれの節に設定例を分割する方が、うまく動かない等で
設定をイジるときも、見る範囲が一定して嬉しいです。

(仕様不明のうまく動かないシステムを触ってると、色々弄りすぎて何が関係あるのか意味不明になりません？)

2020-01-09 09:03 UTC, ohsawa commented
scpしたあとのmvは mv /home/ユーザー名/xxx とした方が良いと思います。
rootなのでディレクトリ違いますし。

2020-01-15 08:21 UTC, yoshidam-at commented
> ダミーのcsvファイルを示して例があると嬉しいです。
少々くどいかもしれませんが、記載してみました。

2020-01-27 02:05 UTC, closed without merging